package bank.java;

public class BankJFrame extends javax.swing.JFrame {
    private final Queue queueAcc = new Queue(6);
    private final Queue queueLoan = new Queue(6);
    private final Queue queueWD = new Queue(16);
    private int ticketAcc = 0;
    private int ticketLoan = 0;
    private int ticketWD = 0;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BankJFrame.class.getName());
    
    public BankJFrame() {
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        LoanPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btnCallLoan = new javax.swing.JButton();
        btnDoneLoan = new javax.swing.JButton();
        AccPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnCallAcc = new javax.swing.JButton();
        btnDoneAcc = new javax.swing.JButton();
        WDPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnCallWD3 = new javax.swing.JButton();
        btnDoneWD3 = new javax.swing.JButton();
        WDPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnCallWD2 = new javax.swing.JButton();
        btnDoneWD2 = new javax.swing.JButton();
        WDPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnCallWD1 = new javax.swing.JButton();
        btnDoneWD1 = new javax.swing.JButton();
        TakequeuePanel = new javax.swing.JPanel();
        btnTakeQueue = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnShowLoan = new javax.swing.JButton();
        btnShowAcc = new javax.swing.JButton();
        btnShowWD = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoanPanel.setBackground(new java.awt.Color(111, 225, 215));
        LoanPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(51, 51, 51), new java.awt.Color(153, 153, 153), new java.awt.Color(51, 51, 51)));

        jLabel8.setText("Loan");
        LoanPanel.add(jLabel8);

        btnCallLoan.setText("Call Queue");
        btnCallLoan.addActionListener(this::btnCallLoanActionPerformed);
        LoanPanel.add(btnCallLoan);

        btnDoneLoan.setText("Done");
        btnDoneLoan.addActionListener(this::btnDoneLoanActionPerformed);
        LoanPanel.add(btnDoneLoan);

        getContentPane().add(LoanPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 230, 120, 110));

        AccPanel.setBackground(new java.awt.Color(237, 142, 148));
        AccPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(51, 51, 51), new java.awt.Color(153, 153, 153), new java.awt.Color(51, 51, 51)));

        jLabel7.setText("Account");
        AccPanel.add(jLabel7);

        btnCallAcc.setText("Call Queue");
        btnCallAcc.addActionListener(this::btnCallAccActionPerformed);
        AccPanel.add(btnCallAcc);

        btnDoneAcc.setText("Done");
        btnDoneAcc.addActionListener(this::btnDoneAccActionPerformed);
        AccPanel.add(btnDoneAcc);

        getContentPane().add(AccPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 80, 120, 110));

        WDPanel3.setBackground(new java.awt.Color(165, 193, 240));
        WDPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(51, 51, 51), new java.awt.Color(153, 153, 153), new java.awt.Color(51, 51, 51)));

        jLabel6.setText("WD3");
        WDPanel3.add(jLabel6);

        btnCallWD3.setText("Call Queue");
        btnCallWD3.addActionListener(this::btnCallWD3ActionPerformed);
        WDPanel3.add(btnCallWD3);

        btnDoneWD3.setText("Done");
        btnDoneWD3.addActionListener(this::btnDoneWD3ActionPerformed);
        WDPanel3.add(btnDoneWD3);

        getContentPane().add(WDPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 120, 100));

        WDPanel2.setBackground(new java.awt.Color(165, 193, 240));
        WDPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(51, 51, 51), new java.awt.Color(153, 153, 153), new java.awt.Color(51, 51, 51)));

        jLabel5.setText("WD2");
        WDPanel2.add(jLabel5);

        btnCallWD2.setText("Call Queue");
        btnCallWD2.addActionListener(this::btnCallWD2ActionPerformed);
        WDPanel2.add(btnCallWD2);

        btnDoneWD2.setText("Done");
        btnDoneWD2.addActionListener(this::btnDoneWD2ActionPerformed);
        WDPanel2.add(btnDoneWD2);

        getContentPane().add(WDPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 120, 100));

        WDPanel1.setBackground(new java.awt.Color(165, 193, 240));
        WDPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(51, 51, 51), new java.awt.Color(153, 153, 153), new java.awt.Color(51, 51, 51)));

        jLabel4.setText("WD1");
        WDPanel1.add(jLabel4);

        btnCallWD1.setText("Call Queue");
        btnCallWD1.addActionListener(this::btnCallWD1ActionPerformed);
        WDPanel1.add(btnCallWD1);

        btnDoneWD1.setText("Done");
        btnDoneWD1.addActionListener(this::btnDoneWD1ActionPerformed);
        WDPanel1.add(btnDoneWD1);

        getContentPane().add(WDPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 120, 100));

        TakequeuePanel.setBackground(new java.awt.Color(0, 204, 0));
        TakequeuePanel.setLayout(new java.awt.GridBagLayout());

        btnTakeQueue.setText("Take a queue ticket");
        btnTakeQueue.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnTakeQueue.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTakeQueue.addActionListener(this::btnTakeQueueActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 6;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        TakequeuePanel.add(btnTakeQueue, gridBagConstraints);

        getContentPane().add(TakequeuePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, 160, 50));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Loan");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 200, 130, 30));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel2.setText("Withdraw / Deposit");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 190, 30));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Account ");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 120, 30));

        btnShowLoan.setText("ShowLoan");
        btnShowLoan.addActionListener(this::btnShowLoanActionPerformed);
        getContentPane().add(btnShowLoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 470, -1, -1));

        btnShowAcc.setText("ShowAcc");
        btnShowAcc.addActionListener(this::btnShowAccActionPerformed);
        getContentPane().add(btnShowAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 470, -1, -1));

        btnShowWD.setText("ShowWD");
        btnShowWD.addActionListener(this::btnShowWDActionPerformed);
        getContentPane().add(btnShowWD, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 470, -1, -1));

        lblBackground.setBackground(new java.awt.Color(153, 255, 102));
        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bank_BG.jpg"))); // NOI18N
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTakeQueueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTakeQueueActionPerformed
        QueueServiceDialog dialog = new QueueServiceDialog(this, true);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        
        String service = dialog.getSelectedService();
        switch (service) {
            case "ACC" -> {
                if (queueAcc.isFull()) {
                    javax.swing.JOptionPane.showMessageDialog(this,"Account queue is full!\nPlease wait...",
                    "Queue Full", javax.swing.JOptionPane.WARNING_MESSAGE);
                } else {
                    ticketAcc++;
                    String ticketA = "A-" + String.format("%03d", ticketAcc);
                    queueAcc.enqueue(ticketA);
                    javax.swing.JOptionPane.showMessageDialog(this,"Queue: " + ticketA + "\nDepartment: Account");
                }
            }
            case "LOAN" -> {
                if (queueLoan.isFull()) {
                    javax.swing.JOptionPane.showMessageDialog(this,"Loan queue is full!\nPlease wait...",
                    "Queue Full", javax.swing.JOptionPane.WARNING_MESSAGE);
                } else {
                    ticketLoan++;
                    String ticketL = "L-" + String.format("%03d", ticketLoan);
                    queueLoan.enqueue(ticketL);
                    javax.swing.JOptionPane.showMessageDialog(this,"Queue: " + ticketL + "\nDepartment: Loan");                
                }
            }
            case "WD" -> {
                if (queueWD.isFull()) {
                    javax.swing.JOptionPane.showMessageDialog(this,"Withdraw/Deposit queue is full!\nPlease wait...",
                    "Queue Full", javax.swing.JOptionPane.WARNING_MESSAGE);
                } else {
                    ticketWD++;
                    String ticketW = "W-" + String.format("%03d", ticketWD);
                    queueWD.enqueue(ticketW);
                    javax.swing.JOptionPane.showMessageDialog(this,"Queue: " + ticketW + "\nDepartment: Withdraw/Deposit");
                }
            }
            default -> {
            }
        }
    }//GEN-LAST:event_btnTakeQueueActionPerformed

    private void btnCallAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCallAccActionPerformed
        String ticket = queueAcc.dequeue();
        if (!ticket.isEmpty()) {
            jLabel7.setText("Account: "+ ticket);
            System.out.println("Done to end this queue");
            btnCallAcc.setEnabled(false); 
            btnDoneAcc.setEnabled(true);
        } else {
            jLabel7.setText("Account: Empty" );
            System.out.println("Queue is empty.");
        }
    }//GEN-LAST:event_btnCallAccActionPerformed

    private void btnDoneAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneAccActionPerformed
        jLabel7.setText("ACCount: Empty");
        btnCallAcc.setEnabled(true);
        btnDoneAcc.setEnabled(false);
    }//GEN-LAST:event_btnDoneAccActionPerformed

    private void btnCallLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCallLoanActionPerformed
        String ticket= queueLoan.dequeue();
        if (!ticket.isEmpty()) {
            jLabel8.setText("Loan: "+ ticket);
            System.out.println("Done to end this queue");
            btnCallLoan.setEnabled(false);
            btnDoneLoan.setEnabled(true);
        } else {
            jLabel8.setText("Loan: Empty" );
            System.out.println("Queue is empty.");
        }
    }//GEN-LAST:event_btnCallLoanActionPerformed

    private void btnDoneLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneLoanActionPerformed
        jLabel8.setText("Loan: Empty");
        btnCallLoan.setEnabled(true);
        btnDoneLoan.setEnabled(false);
    }//GEN-LAST:event_btnDoneLoanActionPerformed

    private void btnCallWD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCallWD1ActionPerformed
        String ticket=queueWD.dequeue();
        if (!ticket.isEmpty()){
            jLabel4.setText("WD1: " + ticket);
            System.out.println("Done to end this queue");
            btnCallWD1.setEnabled(false);
            btnDoneWD1.setEnabled(true);
        } else {
            jLabel4.setText("WD1: Empty");
            System.out.println("Queue is empty.");
        }
    }//GEN-LAST:event_btnCallWD1ActionPerformed

    private void btnDoneWD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneWD1ActionPerformed
       jLabel4.setText("WD1: Empty");
       btnCallWD1.setEnabled(true);
       btnDoneWD1.setEnabled(false);
    }//GEN-LAST:event_btnDoneWD1ActionPerformed

    private void btnCallWD2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCallWD2ActionPerformed
        String ticket=queueWD.dequeue();
        if (!ticket.isEmpty()) {
            jLabel5.setText("WD2: " + ticket);
            btnCallWD2.setEnabled(false);
            btnDoneWD2.setEnabled(true);
        } else {
            jLabel5.setText("WD2: Empty");
            System.out.println("Queue is empty.");
        }
    }//GEN-LAST:event_btnCallWD2ActionPerformed

    private void btnDoneWD2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneWD2ActionPerformed
       jLabel5.setText("WD2: Empty");
       btnCallWD2.setEnabled(true);
       btnDoneWD2.setEnabled(false);
    }//GEN-LAST:event_btnDoneWD2ActionPerformed

    private void btnCallWD3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCallWD3ActionPerformed
        String ticket= queueWD.dequeue();
        if (!ticket.isEmpty()) {
            jLabel6.setText("WD3: " + ticket);
            btnCallWD3.setEnabled(false);
            btnDoneWD3.setEnabled(true);
        } else {
            jLabel6.setText("WD3: Empty");
            System.out.println("Queue is empty.");
        }
    }//GEN-LAST:event_btnCallWD3ActionPerformed

    private void btnDoneWD3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneWD3ActionPerformed
       jLabel6.setText("WD3: Empty");
       btnCallWD3.setEnabled(true);
       btnDoneWD3.setEnabled(false);
    }//GEN-LAST:event_btnDoneWD3ActionPerformed

    private void btnShowAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAccActionPerformed
        System.out.println("==================================");
        System.out.print("Data in Account: ");
        queueAcc.showArr();
        queueAcc.showCurrent();
    }//GEN-LAST:event_btnShowAccActionPerformed

    private void btnShowLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowLoanActionPerformed
        System.out.println("==================================");
        System.out.print("Data in Loan: ");
        queueLoan.showArr();
        queueLoan.showCurrent();
    }//GEN-LAST:event_btnShowLoanActionPerformed

    private void btnShowWDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowWDActionPerformed
        System.out.println("==================================");
        System.out.print("Data in Withdraw/Deposit: ");
        queueWD.showArr();
        queueWD.showCurrent();
    }//GEN-LAST:event_btnShowWDActionPerformed
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new BankJFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AccPanel;
    private javax.swing.JPanel LoanPanel;
    private javax.swing.JPanel TakequeuePanel;
    private javax.swing.JPanel WDPanel1;
    private javax.swing.JPanel WDPanel2;
    private javax.swing.JPanel WDPanel3;
    private javax.swing.JButton btnCallAcc;
    private javax.swing.JButton btnCallLoan;
    private javax.swing.JButton btnCallWD1;
    private javax.swing.JButton btnCallWD2;
    private javax.swing.JButton btnCallWD3;
    private javax.swing.JButton btnDoneAcc;
    private javax.swing.JButton btnDoneLoan;
    private javax.swing.JButton btnDoneWD1;
    private javax.swing.JButton btnDoneWD2;
    private javax.swing.JButton btnDoneWD3;
    private javax.swing.JButton btnShowAcc;
    private javax.swing.JButton btnShowLoan;
    private javax.swing.JButton btnShowWD;
    private javax.swing.JButton btnTakeQueue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblBackground;
    // End of variables declaration//GEN-END:variables
}
