/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package bank.java;

/**
 *
 * @author Natthakit
 */
public class QueueServiceDialog extends javax.swing.JDialog {
    private String selectedService = "";
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(QueueServiceDialog.class.getName());

    /**
     * Creates new form QueueServiceDialog
     */
    public QueueServiceDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAccount = new javax.swing.JButton();
        btnLoan = new javax.swing.JButton();
        btnWithdrawDeposit = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("เลือกคิวที่ต้องการบริการ");

        btnAccount.setText("Account");
        btnAccount.addActionListener(this::btnAccountActionPerformed);

        btnLoan.setText("Loan");
        btnLoan.addActionListener(this::btnLoanActionPerformed);

        btnWithdrawDeposit.setText("Withdraw/Deposit");
        btnWithdrawDeposit.addActionListener(this::btnWithdrawDepositActionPerformed);

        btnBack.setText("←Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btnAccount)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLoan)
                        .addGap(18, 18, 18)
                        .addComponent(btnWithdrawDeposit)))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnBack))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnBack)
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLoan)
                    .addComponent(btnWithdrawDeposit)
                    .addComponent(btnAccount))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();  
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this,"Queue A: Account Service\nPlease wait...");
        selectedService = "ACC";
        this.dispose();
    }//GEN-LAST:event_btnAccountActionPerformed

    private void btnLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoanActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this,"Queue L: Loan Service\nPlease wait...");
        selectedService = "LOAN";
        this.dispose();
    }//GEN-LAST:event_btnLoanActionPerformed

    private void btnWithdrawDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithdrawDepositActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this,"Queue W: Withdraw/Deposit Service\nPlease wait...");
        selectedService = "WD";
        this.dispose();
    }//GEN-LAST:event_btnWithdrawDepositActionPerformed
    public String getSelectedService() {  
        return selectedService;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                QueueServiceDialog dialog = new QueueServiceDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccount;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnLoan;
    private javax.swing.JButton btnWithdrawDeposit;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
